export const cargoOutgoingData = {
    page: "1",
    total: "74195",
    rows: [
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
        {
            cargo_id: "6091139",
            buid: "CTDPS",
            trandate: "2024-06-21 11:31:49",
            trannbr: "_blankCTDPS21103151",
            flight: "GA-0714",
            awb: "123123",
            ori: "DPS",
            dst: "SYD",
            qty: "2",
            total_qty: "2",
            chw: "30",
            sender: "DICKY TES",
            receiver: "DICKY TES",
            create_by: "Dicky firmansyah",
            modified_by: "sg2",
            status: "Open",
        },
    ],
};
