export const cargoIncoming = {
    rows: [
        {
            "cargo_id": "6090825",
            "cis2_id": "662dde1af86e5a9cc84ce57a",
            "payment_id": "0",
            "buid": "CTDPS",
            "trandate": "2024-04-28 13:25:37",
            "btb_date": null,
            "tranout": "0000-00-00 00:00:00",
            "trannbr": "_blankCTDPS28132649",
            "airline_id": "604",
            "flight": "JT-0741",
            "flight_date": "2024-04-28 13:25:37",
            "airline_id_out": "0",
            "flight_out": null,
            "flight_out_date": null,
            "awb": "990-55186331",
            "goodgroup": "General",
            "goodsub": "General Cargo",
            "good": "MANGGA",
            "ori": "PLW",
            "dst": "DPS",
            "qty": "5",
            "total_qty": "5",
            "gw": "205",
            "vol": "0",
            "chw": "205",
            "dom_int": "1",
            "trantipe": "2",
            "shp_id": null,
            "shp_name": "-",
            "shp_addr": "-",
            "shp_loc": "Palu",
            "shp_country": "ID",
            "shp_telp": "",
            "cne_id": null,
            "cne_name": "-",
            "cne_addr": "-",
            "cne_loc": "BALI",
            "cne_country": "ID",
            "cne_telp": "",
            "cne_email": "",
            "agt_id": null,
            "agt_name": "-",
            "agt_addr": "-",
            "agt_loc": "BALI",
            "agt_country": "ID",
            "agt_telp": "",
            "customer_id": "85",
            "sender": "",
            "receiver": "ARIF",
            "kemasan": "",
            "info": "",
            "instruct": "",
            "anomali": "",
            "locked": "1",
            "csd": null,
            "bast": null,
            "released": null,
            "master": "0",
            "house": "0",
            "master_awb": "0",
            "checklist_id": "0",
            "withdrawn": "0",
            "create_by": "fafa.maulana",
            "create_date": "2024-04-28 13:26:49",
            "modified_by": "fafa.maulana",
            "modified_date": "2024-04-28 13:26:49",
            "bpp_id": "0",
            "ra_asal": null,
            "status": "open"
        },
        {
            "cargo_id": "6090805",
            "cis2_id": "662dddc7f86e5a9cc84ce21b",
            "payment_id": "0",
            "buid": "CTDPS",
            "trandate": "2024-04-28 13:23:58",
            "btb_date": null,
            "tranout": "0000-00-00 00:00:00",
            "trannbr": "_blankCTDPS28132526",
            "airline_id": "604",
            "flight": "JT-0741",
            "flight_date": "2024-04-28 13:23:58",
            "airline_id_out": "0",
            "flight_out": null,
            "flight_out_date": null,
            "awb": "990-55186316",
            "goodgroup": "General",
            "goodsub": "General Cargo",
            "good": "MANGGA",
            "ori": "PLW",
            "dst": "DPS",
            "qty": "8",
            "total_qty": "8",
            "gw": "328",
            "vol": "0",
            "chw": "328",
            "dom_int": "1",
            "trantipe": "2",
            "shp_id": null,
            "shp_name": "-",
            "shp_addr": "-",
            "shp_loc": "Palu",
            "shp_country": "ID",
            "shp_telp": "",
            "cne_id": null,
            "cne_name": "-",
            "cne_addr": "-",
            "cne_loc": "BALI",
            "cne_country": "ID",
            "cne_telp": "",
            "cne_email": "",
            "agt_id": null,
            "agt_name": "-",
            "agt_addr": "-",
            "agt_loc": "BALI",
            "agt_country": "ID",
            "agt_telp": "",
            "customer_id": "85",
            "sender": "",
            "receiver": "ARIF",
            "kemasan": "",
            "info": "",
            "instruct": "",
            "anomali": "",
            "locked": "1",
            "csd": null,
            "bast": null,
            "released": null,
            "master": "0",
            "house": "0",
            "master_awb": "0",
            "checklist_id": "0",
            "withdrawn": "0",
            "create_by": "fafa.maulana",
            "create_date": "2024-04-28 13:25:26",
            "modified_by": "fafa.maulana",
            "modified_date": "2024-04-28 13:25:26",
            "bpp_id": "0",
            "ra_asal": null,
            "status": "open"
        },
        {
            "cargo_id": "6090714",
            "cis2_id": "662ddaa1f86e5a9cc84cbf81",
            "payment_id": "0",
            "buid": "CTDPS",
            "trandate": "2024-04-28 13:09:13",
            "btb_date": null,
            "tranout": "0000-00-00 00:00:00",
            "trannbr": "_blankCTDPS28131200",
            "airline_id": "604",
            "flight": "JT-0990",
            "flight_date": "2024-04-28 13:09:13",
            "airline_id_out": "0",
            "flight_out": null,
            "flight_out_date": null,
            "awb": "990-55184360",
            "goodgroup": "General",
            "goodsub": "General Cargo",
            "good": "LAMPIT",
            "ori": "BDJ",
            "dst": "DPS",
            "qty": "2",
            "total_qty": "2",
            "gw": "47",
            "vol": "0",
            "chw": "47",
            "dom_int": "1",
            "trantipe": "2",
            "shp_id": null,
            "shp_name": "-",
            "shp_addr": "-",
            "shp_loc": "Banjarmasin",
            "shp_country": "ID",
            "shp_telp": "",
            "cne_id": null,
            "cne_name": "-",
            "cne_addr": "-",
            "cne_loc": "BALI",
            "cne_country": "ID",
            "cne_telp": "",
            "cne_email": "",
            "agt_id": null,
            "agt_name": "-",
            "agt_addr": "-",
            "agt_loc": "BALI",
            "agt_country": "ID",
            "agt_telp": "",
            "customer_id": "79",
            "sender": "",
            "receiver": "RIYADH",
            "kemasan": "",
            "info": "",
            "instruct": "",
            "anomali": "",
            "locked": "1",
            "csd": null,
            "bast": null,
            "released": null,
            "master": "0",
            "house": "0",
            "master_awb": "0",
            "checklist_id": "0",
            "withdrawn": "0",
            "create_by": "fafa.maulana",
            "create_date": "2024-04-28 13:12:00",
            "modified_by": "fafa.maulana",
            "modified_date": "2024-04-28 13:12:00",
            "bpp_id": "0",
            "ra_asal": null,
            "status": "open"
        },
        {
            "cargo_id": "6090696",
            "cis2_id": "662dd9c9f86e5a9cc84cb7e3",
            "payment_id": "0",
            "buid": "CTDPS",
            "trandate": "2024-04-28 13:07:25",
            "btb_date": null,
            "tranout": "0000-00-00 00:00:00",
            "trannbr": "_blankCTDPS28130824",
            "airline_id": "1099",
            "flight": "ID-7309",
            "flight_date": "2024-04-28 13:07:25",
            "airline_id_out": "0",
            "flight_out": null,
            "flight_out_date": null,
            "awb": "938-41607053",
            "goodgroup": "General",
            "goodsub": "General Cargo",
            "good": "ALKES",
            "ori": "HLP",
            "dst": "DPS",
            "qty": "1",
            "total_qty": "1",
            "gw": "7",
            "vol": "10",
            "chw": "10",
            "dom_int": "1",
            "trantipe": "2",
            "shp_id": null,
            "shp_name": "-",
            "shp_addr": "-",
            "shp_loc": "Halim Perdana Kusuma",
            "shp_country": "ID",
            "shp_telp": "",
            "cne_id": null,
            "cne_name": "-",
            "cne_addr": "-",
            "cne_loc": "BALI",
            "cne_country": "ID",
            "cne_telp": "",
            "cne_email": "",
            "agt_id": null,
            "agt_name": "-",
            "agt_addr": "-",
            "agt_loc": "BALI",
            "agt_country": "ID",
            "agt_telp": "",
            "customer_id": "85",
            "sender": "",
            "receiver": "FARID",
            "kemasan": "",
            "info": "",
            "instruct": "",
            "anomali": "",
            "locked": "1",
            "csd": null,
            "bast": null,
            "released": null,
            "master": "0",
            "house": "0",
            "master_awb": "0",
            "checklist_id": "0",
            "withdrawn": "0",
            "create_by": "fafa.maulana",
            "create_date": "2024-04-28 13:08:24",
            "modified_by": "fafa.maulana",
            "modified_date": "2024-04-28 13:08:24",
            "bpp_id": "0",
            "ra_asal": null,
            "status": "open"
        },
        {
            "cargo_id": "6090684",
            "cis2_id": "662dd922f86e5a9cc84cb41f",
            "payment_id": "0",
            "buid": "CTDPS",
            "trandate": "2024-04-28 13:03:01",
            "btb_date": null,
            "tranout": "0000-00-00 00:00:00",
            "trannbr": "_blankCTDPS28130537",
            "airline_id": "1099",
            "flight": "ID-7309",
            "flight_date": "2024-04-28 13:03:01",
            "airline_id_out": "0",
            "flight_out": null,
            "flight_out_date": null,
            "awb": "938-41605815",
            "goodgroup": "General",
            "goodsub": "General Cargo",
            "good": "SPARTS",
            "ori": "HLP",
            "dst": "DPS",
            "qty": "14",
            "total_qty": "14",
            "gw": "163",
            "vol": "172",
            "chw": "172",
            "dom_int": "1",
            "trantipe": "2",
            "shp_id": null,
            "shp_name": "-",
            "shp_addr": "-",
            "shp_loc": "Halim Perdana Kusuma",
            "shp_country": "ID",
            "shp_telp": "",
            "cne_id": null,
            "cne_name": "-",
            "cne_addr": "-",
            "cne_loc": "BALI",
            "cne_country": "ID",
            "cne_telp": "",
            "cne_email": "",
            "agt_id": null,
            "agt_name": "-",
            "agt_addr": "-",
            "agt_loc": "BALI",
            "agt_country": "ID",
            "agt_telp": "",
            "customer_id": "79",
            "sender": "",
            "receiver": "CKB",
            "kemasan": "",
            "info": "",
            "instruct": "",
            "anomali": "",
            "locked": "1",
            "csd": null,
            "bast": null,
            "released": null,
            "master": "0",
            "house": "0",
            "master_awb": "0",
            "checklist_id": "0",
            "withdrawn": "0",
            "create_by": "fafa.maulana",
            "create_date": "2024-04-28 13:05:37",
            "modified_by": "fafa.maulana",
            "modified_date": "2024-04-28 13:05:37",
            "bpp_id": "0",
            "ra_asal": null,
            "status": "open"
        },
        {
            "cargo_id": "6090650",
            "cis2_id": "662dd751f86e5a9cc84ca4c2",
            "payment_id": "0",
            "buid": "CTDPS",
            "trandate": "2024-04-28 12:55:36",
            "btb_date": null,
            "tranout": "0000-00-00 00:00:00",
            "trannbr": "_blankCTDPS28125752",
            "airline_id": "1099",
            "flight": "ID-7309",
            "flight_date": "2024-04-28 12:55:36",
            "airline_id_out": "0",
            "flight_out": null,
            "flight_out_date": null,
            "awb": "938-41601571",
            "goodgroup": "General",
            "goodsub": "General Cargo",
            "good": "GENCO",
            "ori": "PLM",
            "dst": "DPS",
            "qty": "12",
            "total_qty": "12",
            "gw": "89",
            "vol": "0",
            "chw": "89",
            "dom_int": "1",
            "trantipe": "2",
            "shp_id": null,
            "shp_name": "-",
            "shp_addr": "-",
            "shp_loc": "Palembang",
            "shp_country": "ID",
            "shp_telp": "",
            "cne_id": null,
            "cne_name": "-",
            "cne_addr": "-",
            "cne_loc": "BALI",
            "cne_country": "ID",
            "cne_telp": "",
            "cne_email": "",
            "agt_id": null,
            "agt_name": "-",
            "agt_addr": "-",
            "agt_loc": "BALI",
            "agt_country": "ID",
            "agt_telp": "",
            "customer_id": "77",
            "sender": "",
            "receiver": "JNT",
            "kemasan": "",
            "info": "",
            "instruct": "",
            "anomali": "",
            "locked": "1",
            "csd": null,
            "bast": null,
            "released": null,
            "master": "0",
            "house": "0",
            "master_awb": "0",
            "checklist_id": "0",
            "withdrawn": "0",
            "create_by": "fafa.maulana",
            "create_date": "2024-04-28 12:57:52",
            "modified_by": "fafa.maulana",
            "modified_date": "2024-04-28 12:57:52",
            "bpp_id": "0",
            "ra_asal": null,
            "status": "open"
        },
        {
            "cargo_id": "6090628",
            "cis2_id": "662dd6a6f86e5a9cc84c9ee2",
            "payment_id": "0",
            "buid": "CTDPS",
            "trandate": "2024-04-28 12:52:01",
            "btb_date": null,
            "tranout": "0000-00-00 00:00:00",
            "trannbr": "_blankCTDPS28125500",
            "airline_id": "1099",
            "flight": "ID-7309",
            "flight_date": "2024-04-28 12:52:01",
            "airline_id_out": "0",
            "flight_out": null,
            "flight_out_date": null,
            "awb": "938-41597345",
            "goodgroup": "General",
            "goodsub": "General Cargo",
            "good": "GENCO",
            "ori": "PLM",
            "dst": "DPS",
            "qty": "5",
            "total_qty": "5",
            "gw": "60",
            "vol": "0",
            "chw": "60",
            "dom_int": "1",
            "trantipe": "2",
            "shp_id": null,
            "shp_name": "-",
            "shp_addr": "-",
            "shp_loc": "Palembang",
            "shp_country": "ID",
            "shp_telp": "",
            "cne_id": null,
            "cne_name": "-",
            "cne_addr": "-",
            "cne_loc": "BALI",
            "cne_country": "ID",
            "cne_telp": "",
            "cne_email": "",
            "agt_id": null,
            "agt_name": "-",
            "agt_addr": "-",
            "agt_loc": "BALI",
            "agt_country": "ID",
            "agt_telp": "",
            "customer_id": "77",
            "sender": "",
            "receiver": "JNT",
            "kemasan": "",
            "info": "",
            "instruct": "",
            "anomali": "",
            "locked": "1",
            "csd": null,
            "bast": null,
            "released": null,
            "master": "0",
            "house": "0",
            "master_awb": "0",
            "checklist_id": "0",
            "withdrawn": "0",
            "create_by": "fafa.maulana",
            "create_date": "2024-04-28 12:55:00",
            "modified_by": "fafa.maulana",
            "modified_date": "2024-04-28 12:55:00",
            "bpp_id": "0",
            "ra_asal": null,
            "status": "open"
        },
        {
            "cargo_id": "6090608",
            "cis2_id": "662dd5dff86e5a9cc84c97b1",
            "payment_id": "0",
            "buid": "CTDPS",
            "trandate": "2024-04-28 12:50:27",
            "btb_date": null,
            "tranout": "0000-00-00 00:00:00",
            "trannbr": "_blankCTDPS28125143",
            "airline_id": "1099",
            "flight": "ID-7309",
            "flight_date": "2024-04-28 12:50:27",
            "airline_id_out": "0",
            "flight_out": null,
            "flight_out_date": null,
            "awb": "938-41597301",
            "goodgroup": "General",
            "goodsub": "General Cargo",
            "good": "GENCO",
            "ori": "PLM",
            "dst": "DPS",
            "qty": "15",
            "total_qty": "15",
            "gw": "179",
            "vol": "0",
            "chw": "179",
            "dom_int": "1",
            "trantipe": "2",
            "shp_id": null,
            "shp_name": "-",
            "shp_addr": "-",
            "shp_loc": "Palembang",
            "shp_country": "ID",
            "shp_telp": "",
            "cne_id": null,
            "cne_name": "-",
            "cne_addr": "-",
            "cne_loc": "BALI",
            "cne_country": "ID",
            "cne_telp": "",
            "cne_email": "",
            "agt_id": null,
            "agt_name": "-",
            "agt_addr": "-",
            "agt_loc": "BALI",
            "agt_country": "ID",
            "agt_telp": "",
            "customer_id": "77",
            "sender": "",
            "receiver": "JNT",
            "kemasan": "",
            "info": "",
            "instruct": "",
            "anomali": "",
            "locked": "1",
            "csd": null,
            "bast": null,
            "released": null,
            "master": "0",
            "house": "0",
            "master_awb": "0",
            "checklist_id": "0",
            "withdrawn": "0",
            "create_by": "fafa.maulana",
            "create_date": "2024-04-28 12:51:43",
            "modified_by": "fafa.maulana",
            "modified_date": "2024-04-28 12:51:50",
            "bpp_id": "0",
            "ra_asal": null,
            "status": "open"
        },
        {
            "cargo_id": "6090592",
            "cis2_id": "662dd561f86e5a9cc84c93db",
            "payment_id": "0",
            "buid": "CTDPS",
            "trandate": "2024-04-28 12:46:37",
            "btb_date": null,
            "tranout": "0000-00-00 00:00:00",
            "trannbr": "_blankCTDPS28124936",
            "airline_id": "1099",
            "flight": "ID-7309",
            "flight_date": "2024-04-28 12:46:37",
            "airline_id_out": "0",
            "flight_out": null,
            "flight_out_date": null,
            "awb": "938-41597275",
            "goodgroup": "General",
            "goodsub": "General Cargo",
            "good": "GENCO",
            "ori": "PLM",
            "dst": "DPS",
            "qty": "15",
            "total_qty": "15",
            "gw": "186",
            "vol": "0",
            "chw": "186",
            "dom_int": "1",
            "trantipe": "2",
            "shp_id": null,
            "shp_name": "- ",
            "shp_addr": "-",
            "shp_loc": "Palembang",
            "shp_country": "ID",
            "shp_telp": "",
            "cne_id": null,
            "cne_name": "-",
            "cne_addr": "-",
            "cne_loc": "BALI",
            "cne_country": "ID",
            "cne_telp": "",
            "cne_email": "",
            "agt_id": null,
            "agt_name": "-",
            "agt_addr": "-",
            "agt_loc": "BALI",
            "agt_country": "ID",
            "agt_telp": "",
            "customer_id": "77",
            "sender": "",
            "receiver": "JNT",
            "kemasan": "",
            "info": "",
            "instruct": "",
            "anomali": "",
            "locked": "1",
            "csd": null,
            "bast": null,
            "released": null,
            "master": "0",
            "house": "0",
            "master_awb": "0",
            "checklist_id": "0",
            "withdrawn": "0",
            "create_by": "fafa.maulana",
            "create_date": "2024-04-28 12:49:36",
            "modified_by": "fafa.maulana",
            "modified_date": "2024-04-28 12:49:36",
            "bpp_id": "0",
            "ra_asal": null,
            "status": "open"
        },
        {
            "cargo_id": "6090531",
            "cis2_id": "662dd3ccf86e5a9cc84c866f",
            "payment_id": "0",
            "buid": "CTDPS",
            "trandate": "2024-04-28 12:38:18",
            "btb_date": null,
            "tranout": "0000-00-00 00:00:00",
            "trannbr": "_blankCTDPS28124251",
            "airline_id": "604",
            "flight": "JT-0990",
            "flight_date": "2024-04-28 12:38:18",
            "airline_id_out": "0",
            "flight_out": null,
            "flight_out_date": null,
            "awb": "990-55185513",
            "goodgroup": "General",
            "goodsub": "General Cargo",
            "good": "FRESH FISH",
            "ori": "KOE",
            "dst": "DPS",
            "qty": "11",
            "total_qty": "11",
            "gw": "348",
            "vol": "0",
            "chw": "348",
            "dom_int": "1",
            "trantipe": "2",
            "shp_id": null,
            "shp_name": "-",
            "shp_addr": "-",
            "shp_loc": "Kupang",
            "shp_country": "ID",
            "shp_telp": "",
            "cne_id": null,
            "cne_name": "-",
            "cne_addr": "-",
            "cne_loc": "BALI",
            "cne_country": "ID",
            "cne_telp": "",
            "cne_email": "",
            "agt_id": null,
            "agt_name": "-",
            "agt_addr": "-",
            "agt_loc": "BALI",
            "agt_country": "ID",
            "agt_telp": "",
            "customer_id": "76",
            "sender": "",
            "receiver": "IM BE U",
            "kemasan": "",
            "info": "",
            "instruct": "",
            "anomali": "",
            "locked": "1",
            "csd": null,
            "bast": null,
            "released": null,
            "master": "0",
            "house": "0",
            "master_awb": "0",
            "checklist_id": "0",
            "withdrawn": "0",
            "create_by": "fafa.maulana",
            "create_date": "2024-04-28 12:42:51",
            "modified_by": "fafa.maulana",
            "modified_date": "2024-04-28 12:42:51",
            "bpp_id": "0",
            "ra_asal": null,
            "status": "open"
        }
    ]
}
